ARG BASE_IMAGE=python:3.10-slim-bullseye
FROM ${BASE_IMAGE}
RUN apt-get update \
	&& apt-get install build-essential git gcc -y \
	&& apt-get clean

RUN mkdir /data
COPY ../ /data

RUN pip3 install -r /data/requirements.txt
RUN pip3 install -r /data/requirements.dev.txt

WORKDIR /data/src

EXPOSE 8000

CMD ""