ARG BASE_IMAGE=python:3.10-slim-bullseye
FROM ${BASE_IMAGE}
RUN apt-get update \
	&& apt-get install build-essential git gcc -y \
	&& apt-get clean

RUN mkdir /data
COPY ../requirements.txt /
COPY ../requirements.dev.txt /

RUN pip3 install -r /requirements.txt
RUN pip3 install -r /requirements.dev.txt

WORKDIR /data/src

EXPOSE 8000

CMD ""