version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
  
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - .env
    command: "/bin/sh -c \"while sleep 1000; do :; done\""
    depends_on:
      - postgres

volumes:
    postgres_test_data: